# Generated by Django 4.2.5 on 2023-09-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professores',
            fields=[
                ('id_professor', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=256)),
                ('cpf', models.CharField(max_length=11)),
                ('rg', models.CharField(max_length=8)),
                ('codigo', models.CharField(max_length=8)),
                ('email', models.CharField(max_length=256)),
                ('telefone', models.CharField(max_length=256)),
            ],
        ),
    ]
