# Generated by Django 4.2.5 on 2023-09-22 14:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('id_alunos', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11)),
                ('rg', models.CharField(max_length=8)),
                ('matricula', models.CharField(max_length=8)),
                ('telefone', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id_atividade', models.AutoField(primary_key=True, serialize=False)),
                ('atividade', models.TextField()),
                ('tipo', models.CharField(max_length=50)),
                ('data_postagem', models.DateTimeField(verbose_name=datetime.date.today)),
                ('data_entrega', models.DateTimeField(verbose_name=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplinas',
            fields=[
                ('id_disciplina', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('codigo', models.CharField(max_length=7)),
                ('carga_horaria', models.IntegerField()),
                ('ementa', models.TextField()),
                ('id_professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.professores')),
            ],
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id_frequencia', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.DateTimeField(verbose_name=datetime.date.today)),
                ('id_materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.disciplinas')),
            ],
        ),
        migrations.CreateModel(
            name='PlanoAula',
            fields=[
                ('id_plano_aula', models.AutoField(primary_key=True, serialize=False)),
                ('tema_aula', models.CharField(max_length=255)),
                ('conteudo', models.TextField()),
                ('metodo', models.CharField(max_length=50)),
                ('dia', models.DateTimeField(verbose_name=datetime.date.today)),
                ('id_disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.disciplinas')),
            ],
        ),
        migrations.CreateModel(
            name='FrequenciaAluno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.alunos')),
                ('id_frequencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.frequencia')),
            ],
        ),
        migrations.CreateModel(
            name='DisciplinaAluno',
            fields=[
                ('id_matricula', models.AutoField(primary_key=True, serialize=False)),
                ('nota', models.FloatField()),
                ('id_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.alunos')),
                ('id_disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.disciplinas')),
            ],
        ),
        migrations.CreateModel(
            name='AtividadeAluno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nota', models.FloatField()),
                ('id_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.alunos')),
                ('id_atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.atividade')),
            ],
        ),
        migrations.AddField(
            model_name='atividade',
            name='id_disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.disciplinas'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='id_plano_aula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.planoaula'),
        ),
    ]
